spring.application.name=api-gateway
server.port=9090

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

account.service.urls=http://localhost:8080,http://localhost:8083
transfer.service.url=http://localhost:8081

logging.structured.format.console=ecs
